name: MediaWarp Binary Builder

on:
  workflow_call:
    inputs:
      APP_VERSION:
        description: "用于生成可执行文件的版本号"
        required: true
        type: string

env:
  APP_VERSION: ${{ inputs.APP_VERSION }}
  APP_NAME: MediaWarp
  BINARY_DIR: ${{ github.workspace }}/bin

jobs:
  binary-builder:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          os: [linux, windows, darwin]
          arch: [amd64, arm64]
          
      steps:
        - name: Show Information
          run: |
            echo "项目名：${{ env.APP_NAME }}"
            echo "版本号：${{ env.APP_VERSION }}"
            echo "操作系统：${{ matrix.os }}"
            echo "架构：${{ matrix.arch }}"
            echo "可执行文件：${{ env.APP_NAME }}-${{ env.APP_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}"

        - name: Clone Repository
          uses: actions/checkout@v4

        - name: Set Up Golong Environment
          uses: actions/setup-go@v5
          with:
            go-version: "1.22.5"

        - name: Build Binary for ${{ matrix.os }}-${{ matrix.arch }}
          run: |
            GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.BINARY_DIR }}/${{ env.APP_NAME }}-${{ env.APP_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

        - name: Upload Binary
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
            path: ${{ env.BINARY_DIR }}/${{ env.APP_NAME }}-${{ env.APP_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

